
[light_sources]
	entities = true
	self = true
	block_entities = true
	water_sensitive_check = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				player = true
				cat = true
				item = true
				creeper = true
				experience_orb = true
				bat = true
				zombie = true
				skeleton = true
				spider = true
				enderman = true
				witch = true
				husk = true
				arrow = true
				bee = true
				villager = true
				slime = true
				leash_knot = true
				wandering_trader = true
				trader_llama = true
				iron_golem = true

			[light_sources.settings.entities.alexsmobs]
				cockroach = true
				fly = true
				crow = true

			[light_sources.settings.entities.mekanismadditions]
				baby_creeper = true
				baby_skeleton = true
				baby_enderman = true

			[light_sources.settings.entities.endermanoverhaul]
				mushroom_fields_enderman = true

			[light_sources.settings.entities.creeperoverhaul]
				cave_creeper = true

			[light_sources.settings.entities.graveyard]
				skeleton_creeper = true

			[light_sources.settings.entities.goblintraders]
				goblin_trader = true

			[light_sources.settings.entities.guardvillagers]
				guard = true

